let data;
export default data = {
    guid:'fake',
    "typo":"条目类型(可为空)",
    "primary_name":"音乐原名",
    "zh_name":"中文名（若没有可与primary_name相同）",
    "description":"条目内容描述",
    "singer":["歌手","歌手2"],
    "arranger":["编曲人","编曲人2"],
    "composer":["作曲人","作曲人2"],
    "lyrics":["作词人"],
    "names":[
        "别名1",
        "别名2",
    ],
    "tags":[
        "标签1",
        "标签2",
    ],
    "related_subjects":[
        "关联条目1",
        "关联条目2",
    ],
    "visuals":[
        "https://lain.bgm.tv/pic/cover/l/c1/03/316050_8q89c.jpg",
        "图片url2",
    ],
    "extra_data":"以防有未定义过的类型（可为空）",
}
